add backend template
vladdan16/spda-afisha pull request #1
Opened 2024-03-10 17:22 UTC by vladdan16

2024-03-10 18:51 UTC, NAD777 requested changes

2024-03-10 18:51 UTC, NAD777 commented on backend/src/main/java/com/vladdan16/spda_afisha/backend/dto/responses/ApiErrorResponse.java
> +                               List<String> stacktrace) {
А мы хотим стектрейс пользователю кидать? 
Или планируется это потом выпилить, пока в дебаг целях?

2024-03-10 18:51 UTC, NAD777 commented on backend/src/main/java/com/vladdan16/spda_afisha/backend/domain/models/User.java
> +@Table(name = "user")
Давай с большой сделаем, как никак название таблицы

2024-03-10 18:51 UTC, NAD777 commented on backend/src/main/java/com/vladdan16/spda_afisha/backend/domain/models/User.java
> +public class User {
Можешь еще сделать enum, как у нас заявлено в базе? Я не java девелопер, мб сталкивался уже. Да и остальные поля можно, не думаю, что это большая работа

2024-03-10 18:51 UTC, NAD777 commented on backend/src/main/java/com/vladdan16/spda_afisha/backend/dto/requests/CreateEventRequest.java
> +public record CreateEventRequest(String name, String type,
Давай подобные штуки писать (где большой конструктор или метод)
```java
public record CreateEventRequest(
   String name,
   String type
   ...
)
```

2024-03-10 18:51 UTC, NAD777 commented on backend/src/main/java/com/vladdan16/spda_afisha/backend/service/jpa/JpaEventService.java
> +  public void createEvent(String name, String type, OffsetDateTime startAt, Long numberSeats, String description) {
Длинные сигнатуры тоже бы в несколько строк, а то тоска

2024-03-10 19:46 UTC, vladdan16 commented on backend/src/main/java/com/vladdan16/spda_afisha/backend/domain/models/User.java
> +public class User {
Да все сделаем, оф коурс, я ж просто шаблон сделал даже не смотря на схему в ноушен. Потом уже будем сидеть запариваться над тем, что все с бэком и ноушеном согласованно было.

2024-03-10 19:46 UTC, vladdan16 commented on backend/src/main/java/com/vladdan16/spda_afisha/backend/domain/models/User.java
> +public class User {
На то и тудушки везде висят. Как говорится бери да делай!

2024-03-10 21:07 UTC, NAD777 commented on backend/src/main/java/com/vladdan16/spda_afisha/backend/domain/models/User.java
> +public class User {
Да, я понимаю, я скорее про то, если ты знаешь как сделать enum, это улучшит шаблон. И следующий более просто напишет новое

2024-03-13 15:50 UTC, r-mol requested changes

2024-03-13 15:50 UTC, r-mol commented on backend/src/main/java/com/vladdan16/spda_afisha/backend/domain/models/User.java
> +@Table(name = "user")
Да поддерживаю, принято писать с заглавной буквы

2024-03-13 15:50 UTC, r-mol commented on backend/src/main/java/com/vladdan16/spda_afisha/backend/domain/repositories/UserRepository.java
> +public interface UserRepository extends JpaRepository<User, Long> {
А где методы или тудушки?

2024-03-13 15:50 UTC, r-mol commented on backend/src/main/java/com/vladdan16/spda_afisha/backend/dto/requests/SignupRequest.java
> +public record SignupRequest(String login, String password) {
Такая же проблема в стелистики как и выше

2024-03-13 16:12 UTC, vladdan16 commented on backend/src/main/java/com/vladdan16/spda_afisha/backend/domain/repositories/UserRepository.java
> +public interface UserRepository extends JpaRepository<User, Long> {
Тсссс, это магия Hibernate, тут ничего не должно быть

2024-03-13 18:38 UTC, vladdan16 commented on backend/src/main/java/com/vladdan16/spda_afisha/backend/dto/responses/ApiErrorResponse.java
> +                               List<String> stacktrace) {
Убрал

2024-03-13 18:38 UTC, vladdan16 commented on backend/src/main/java/com/vladdan16/spda_afisha/backend/domain/models/User.java
> +@Table(name = "user")
Ладно.

2024-03-13 18:39 UTC, vladdan16 commented on backend/src/main/java/com/vladdan16/spda_afisha/backend/domain/models/User.java
> +public class User {
Добавил.

2024-03-13 18:39 UTC, vladdan16 commented on backend/src/main/java/com/vladdan16/spda_afisha/backend/dto/requests/CreateEventRequest.java
> +public record CreateEventRequest(String name, String type,
Хорошо.

2024-03-13 18:39 UTC, vladdan16 commented on backend/src/main/java/com/vladdan16/spda_afisha/backend/service/jpa/JpaEventService.java
> +  public void createEvent(String name, String type, OffsetDateTime startAt, Long numberSeats, String description) {
Оке

2024-03-13 18:46 UTC, NAD777 approved these changes

2024-03-14 18:45 UTC, r-mol approved these changes

2024-03-14 18:47 UTC, merged